# Generated by Django 5.1.6 on 2025-02-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='total_points_earned',
            field=models.IntegerField(default=0),
        ),
    ]
