# Generated by Django 5.1.6 on 2025-02-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_userpoints_total_points_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstransaction',
            name='redemption_item',
            field=models.CharField(blank=True, choices=[('tree', 'Tree'), ('succulent', 'Succulent'), ('produce', 'Produce')], help_text="Specifies which item was redeemed if transaction_type='redeem'.", max_length=20, null=True),
        ),
    ]
